# Generated by Django 4.2.7 on 2026-02-18 13:40

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_organizationtransaction_balance_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_category',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='order',
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='product',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='productsize',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='producttag',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='producttag',
            name='product',
        ),
        migrations.RemoveField(
            model_name='producttag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='size',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
        migrations.AlterField(
            model_name='balancetransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Пополнение'), ('withdrawal', 'Вывод'), ('order_payment', 'Оплата заказа'), ('order_refund', 'Возврат заказа'), ('course_payment', 'Оплата курса'), ('course_refund', 'Возврат за курс')], max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='included_content',
            field=models.TextField(blank=True, help_text='Описание состава курса для карточки (что входит в программу)', null=True, verbose_name='Что входит в состав курса'),
        ),
        migrations.AlterField(
            model_name='coursecontentpage',
            name='content_type',
            field=models.CharField(choices=[('pdf_page', 'Страница PDF'), ('youtube', 'YouTube (видео)'), ('rutube', 'Rutube (видео)'), ('pptx_slide', 'PowerPoint презентация'), ('docx', 'Документ Word'), ('video', 'Видео (файл)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='coursecontentpage',
            name='file_path',
            field=models.CharField(help_text='Путь к файлу (PDF/PPTX/DOCX) или ссылка (для YouTube/Rutube)', max_length=500),
        ),
        migrations.AlterField(
            model_name='coursecontentpage',
            name='page_number',
            field=models.PositiveIntegerField(blank=True, help_text='Номер страницы PDF или слайда (для файлов)', null=True),
        ),
        migrations.AlterField(
            model_name='courseimage',
            name='image_path',
            field=models.CharField(max_length=500, verbose_name='Путь/URL изображения'),
        ),
        migrations.AlterField(
            model_name='courseimage',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='courseimage',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, help_text='0–3 для 4 фото'),
        ),
        migrations.AlterField(
            model_name='coursepurchase',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Переведён в архив (просмотр до конца + опрос + отзыв)'),
        ),
        migrations.AlterField(
            model_name='coursepurchase',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Банковская карта'), ('sbp', 'СБП'), ('balance', 'Баланс')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coursepurchase',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('paid', 'Оплачен'), ('refunded', 'Возврат'), ('cancelled', 'Отменён')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Стоимость доставки'),
        ),
        migrations.AlterField(
            model_name='organizationtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('order_payment', 'Поступление от заказа'), ('order_refund', 'Возврат по отмене заказа'), ('course_payment', 'Поступление от курса'), ('course_refund', 'Возврат за курс'), ('tax_payment', 'Оплата налога'), ('withdrawal', 'Вывод на карту админа')], max_length=20),
        ),
        migrations.AlterField(
            model_name='promousage',
            name='order',
            field=models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.order'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
        migrations.DeleteModel(
            name='ProductTag',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
